import React, { useState, useEffect } from 'react';
import { X } from 'lucide-react';
import type { PhoneNumber, SipTrunkCredential } from '../types';
import { createPhoneNumber, getSipTrunkCredentials } from '../services/callyyService';

interface PhoneNumberModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSuccess: (phoneNumber: PhoneNumber) => void;
}

type ProviderType = 'Callyy' | 'CallyySIP' | 'Twilio' | 'Vonage' | 'Telnyx' | 'BYOSIP';

const PhoneNumberModal: React.FC<PhoneNumberModalProps> = ({ isOpen, onClose, onSuccess }) => {
    const [selectedProvider, setSelectedProvider] = useState<ProviderType>('Callyy');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [sipCredentials, setSipCredentials] = useState<SipTrunkCredential[]>([]);

    // Form fields for different providers
    const [areaCode, setAreaCode] = useState('');
    const [sipIdentifier, setSipIdentifier] = useState('');
    const [sipLabel, setSipLabel] = useState('');
    const [sipUsername, setSipUsername] = useState('');
    const [sipPassword, setSipPassword] = useState('');
    const [twilioPhoneNumber, setTwilioPhoneNumber] = useState('');
    const [twilioAccountSid, setTwilioAccountSid] = useState('');
    const [twilioAuthToken, setTwilioAuthToken] = useState('');
    const [smsEnabled, setSmsEnabled] = useState(false);
    const [vonagePhoneNumber, setVonagePhoneNumber] = useState('');
    const [vonageApiKey, setVonageApiKey] = useState('');
    const [vonageApiSecret, setVonageApiSecret] = useState('');
    const [telnyxPhoneNumber, setTelnyxPhoneNumber] = useState('');
    const [telnyxApiKey, setTelnyxApiKey] = useState('');
    const [sipTrunkPhoneNumber, setSipTrunkPhoneNumber] = useState('');
    const [sipTrunkCredentialId, setSipTrunkCredentialId] = useState('');
    const [allowNonE164, setAllowNonE164] = useState(false);
    const [label, setLabel] = useState('');

    useEffect(() => {
        if (isOpen && selectedProvider === 'BYOSIP') {
            loadSipCredentials();
        }
    }, [isOpen, selectedProvider]);

    const loadSipCredentials = async () => {
        try {
            const credentials = await getSipTrunkCredentials();
            setSipCredentials(credentials);
        } catch (err) {
            console.error('Error loading SIP credentials:', err);
        }
    };

    const resetForm = () => {
        setAreaCode('');
        setSipIdentifier('');
        setSipLabel('');
        setSipUsername('');
        setSipPassword('');
        setTwilioPhoneNumber('');
        setTwilioAccountSid('');
        setTwilioAuthToken('');
        setSmsEnabled(false);
        setVonagePhoneNumber('');
        setVonageApiKey('');
        setVonageApiSecret('');
        setTelnyxPhoneNumber('');
        setTelnyxApiKey('');
        setSipTrunkPhoneNumber('');
        setSipTrunkCredentialId('');
        setAllowNonE164(false);
        setLabel('');
        setError(null);
    };

    const handleClose = () => {
        resetForm();
        onClose();
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        setError(null);

        try {
            let phoneNumberData: Omit<PhoneNumber, 'id'>;

            switch (selectedProvider) {
                case 'Callyy':
                    if (!areaCode) {
                        setError('Area code is required');
                        setLoading(false);
                        return;
                    }
                    phoneNumberData = {
                        number: `+1${areaCode}XXXXXXX`, // Placeholder, will be generated by backend
                        provider: 'Callyy',
                        areaCode,
                        label: label || 'Free Callyy Number',
                        inboundEnabled: true,
                        outboundEnabled: false,
                        isActive: true
                    };
                    break;

                case 'CallyySIP':
                    if (!sipIdentifier) {
                        setError('SIP identifier is required');
                        setLoading(false);
                        return;
                    }
                    phoneNumberData = {
                        number: `sip:${sipIdentifier}@sip.callyy.ai`,
                        provider: 'CallyySIP',
                        sipIdentifier,
                        sipLabel: sipLabel || 'Free Callyy SIP',
                        sipUsername,
                        sipPassword,
                        label: label || sipLabel || 'Free Callyy SIP',
                        inboundEnabled: true,
                        outboundEnabled: false,
                        isActive: true
                    };
                    break;

                case 'Twilio':
                    if (!twilioPhoneNumber || !twilioAccountSid || !twilioAuthToken) {
                        setError('All Twilio fields are required');
                        setLoading(false);
                        return;
                    }
                    phoneNumberData = {
                        number: twilioPhoneNumber,
                        provider: 'Twilio',
                        twilioPhoneNumber,
                        twilioAccountSid,
                        twilioAuthToken,
                        smsEnabled,
                        label: label || 'Twilio Number',
                        inboundEnabled: true,
                        outboundEnabled: true,
                        isActive: true
                    };
                    break;

                case 'Vonage':
                    if (!vonagePhoneNumber || !vonageApiKey || !vonageApiSecret) {
                        setError('All Vonage fields are required');
                        setLoading(false);
                        return;
                    }
                    phoneNumberData = {
                        number: vonagePhoneNumber,
                        provider: 'Vonage',
                        vonagePhoneNumber,
                        vonageApiKey,
                        vonageApiSecret,
                        label: label || 'Vonage Number',
                        inboundEnabled: true,
                        outboundEnabled: true,
                        isActive: true
                    };
                    break;

                case 'Telnyx':
                    if (!telnyxPhoneNumber || !telnyxApiKey) {
                        setError('All Telnyx fields are required');
                        setLoading(false);
                        return;
                    }
                    phoneNumberData = {
                        number: telnyxPhoneNumber,
                        provider: 'Telnyx',
                        telnyxPhoneNumber,
                        telnyxApiKey,
                        label: label || 'Telnyx Number',
                        inboundEnabled: true,
                        outboundEnabled: true,
                        isActive: true
                    };
                    break;

                case 'BYOSIP':
                    if (!sipTrunkPhoneNumber || !sipTrunkCredentialId) {
                        setError('Phone number and SIP trunk credential are required');
                        setLoading(false);
                        return;
                    }
                    phoneNumberData = {
                        number: sipTrunkPhoneNumber,
                        provider: 'BYOSIP',
                        sipTrunkPhoneNumber,
                        sipTrunkCredentialId,
                        allowNonE164,
                        label: label || 'BYO SIP Trunk',
                        inboundEnabled: true,
                        outboundEnabled: true,
                        isActive: true
                    };
                    break;

                default:
                    setError('Invalid provider selected');
                    setLoading(false);
                    return;
            }

            const result = await createPhoneNumber(phoneNumberData);
            
            if (result) {
                onSuccess(result);
                handleClose();
            } else {
                setError('Failed to create phone number. Please try again.');
            }
        } catch (err) {
            console.error('Error creating phone number:', err);
            setError('An error occurred. Please try again.');
        } finally {
            setLoading(false);
        }
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4">
            <div className="bg-background border border-border rounded-2xl max-w-5xl w-full max-h-[90vh] overflow-hidden flex">
                {/* Left Sidebar - Provider Options */}
                <div className="w-80 bg-surface border-r border-border p-6 overflow-y-auto">
                    <h3 className="text-sm font-medium text-textMuted mb-4">Phone Number Options</h3>
                    
                    <div className="space-y-2">
                        <button
                            type="button"
                            onClick={() => setSelectedProvider('Callyy')}
                            className={`w-full text-left px-4 py-3 rounded-lg transition-all ${
                                selectedProvider === 'Callyy'
                                    ? 'bg-primary/10 border-2 border-primary text-primary'
                                    : 'bg-background border border-border text-textMain hover:bg-surfaceHover'
                            }`}
                        >
                            Free Callyy Number
                        </button>

                        <button
                            type="button"
                            onClick={() => setSelectedProvider('CallyySIP')}
                            className={`w-full text-left px-4 py-3 rounded-lg transition-all ${
                                selectedProvider === 'CallyySIP'
                                    ? 'bg-primary/10 border-2 border-primary text-primary'
                                    : 'bg-background border border-border text-textMain hover:bg-surfaceHover'
                            }`}
                        >
                            Free Callyy SIP
                        </button>

                        <button
                            type="button"
                            onClick={() => setSelectedProvider('Twilio')}
                            className={`w-full text-left px-4 py-3 rounded-lg transition-all ${
                                selectedProvider === 'Twilio'
                                    ? 'bg-primary/10 border-2 border-primary text-primary'
                                    : 'bg-background border border-border text-textMain hover:bg-surfaceHover'
                            }`}
                        >
                            Import Twilio
                        </button>

                        <button
                            type="button"
                            onClick={() => setSelectedProvider('Vonage')}
                            className={`w-full text-left px-4 py-3 rounded-lg transition-all ${
                                selectedProvider === 'Vonage'
                                    ? 'bg-primary/10 border-2 border-primary text-primary'
                                    : 'bg-background border border-border text-textMain hover:bg-surfaceHover'
                            }`}
                        >
                            Import Vonage
                        </button>

                        <button
                            type="button"
                            onClick={() => setSelectedProvider('Telnyx')}
                            className={`w-full text-left px-4 py-3 rounded-lg transition-all ${
                                selectedProvider === 'Telnyx'
                                    ? 'bg-primary/10 border-2 border-primary text-primary'
                                    : 'bg-background border border-border text-textMain hover:bg-surfaceHover'
                            }`}
                        >
                            Import Telnyx
                        </button>

                        <button
                            type="button"
                            onClick={() => setSelectedProvider('BYOSIP')}
                            className={`w-full text-left px-4 py-3 rounded-lg transition-all ${
                                selectedProvider === 'BYOSIP'
                                    ? 'bg-primary/10 border-2 border-primary text-primary'
                                    : 'bg-background border border-border text-textMain hover:bg-surfaceHover'
                            }`}
                        >
                            BYO SIP Trunk Number
                        </button>
                    </div>
                </div>

                {/* Right Side - Form */}
                <div className="flex-1 flex flex-col">
                    {/* Header */}
                    <div className="flex justify-between items-center p-6 border-b border-border">
                        <h2 className="text-xl font-bold text-textMain">Add Phone Number</h2>
                        <button
                            onClick={handleClose}
                            className="text-textMuted hover:text-textMain transition-colors"
                        >
                            <X size={24} />
                        </button>
                    </div>

                    {/* Form Content */}
                    <form onSubmit={handleSubmit} className="flex-1 overflow-y-auto p-6">
                        {error && (
                            <div className="mb-4 p-3 bg-red-500/10 border border-red-500/50 rounded-lg text-red-400 text-sm">
                                {error}
                            </div>
                        )}

                        {/* Free Callyy Number Form */}
                        {selectedProvider === 'Callyy' && (
                            <div className="space-y-4">
                                <div>
                                    <label className="block text-sm font-medium text-textMain mb-2">
                                        Area Code
                                    </label>
                                    <input
                                        type="text"
                                        value={areaCode}
                                        onChange={(e) => setAreaCode(e.target.value)}
                                        placeholder="e.g. 346, 984, 326"
                                        className="w-full px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                        maxLength={3}
                                    />
                                    <p className="text-xs text-primary mt-2 flex items-start gap-2">
                                        <span className="text-base">ℹ️</span>
                                        <span>Free US phone numbers • Up to 10 per account<br />
                                        Only US area codes are supported. For international numbers, use the import options above.</span>
                                    </p>
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-textMain mb-2">
                                        Label (Optional)
                                    </label>
                                    <input
                                        type="text"
                                        value={label}
                                        onChange={(e) => setLabel(e.target.value)}
                                        placeholder="Label for Phone Number"
                                        className="w-full px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                    />
                                </div>
                            </div>
                        )}

                        {/* Free Callyy SIP Form */}
                        {selectedProvider === 'CallyySIP' && (
                            <div className="space-y-4">
                                <div>
                                    <label className="block text-sm font-medium text-textMain mb-2">
                                        SIP Identifier
                                    </label>
                                    <input
                                        type="text"
                                        value={sipIdentifier}
                                        onChange={(e) => setSipIdentifier(e.target.value)}
                                        placeholder="my-example-identifier"
                                        className="w-full px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                    />
                                    <p className="text-xs text-textMuted mt-1">
                                        Will be used as: sip:identifier@sip.callyy.ai
                                    </p>
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-textMain mb-2">
                                        Label
                                    </label>
                                    <input
                                        type="text"
                                        value={sipLabel}
                                        onChange={(e) => setSipLabel(e.target.value)}
                                        placeholder="Label for SIP URI"
                                        className="w-full px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                    />
                                </div>

                                <div className="border-t border-border pt-4">
                                    <h4 className="text-sm font-medium text-textMain mb-3">SIP Authentication (Optional)</h4>
                                    
                                    <div className="space-y-3">
                                        <div>
                                            <label className="block text-sm text-textMuted mb-1">Username</label>
                                            <input
                                                type="text"
                                                value={sipUsername}
                                                onChange={(e) => setSipUsername(e.target.value)}
                                                placeholder="SIP Authentication Username"
                                                className="w-full px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                            />
                                        </div>

                                        <div>
                                            <label className="block text-sm text-textMuted mb-1">Password</label>
                                            <input
                                                type="password"
                                                value={sipPassword}
                                                onChange={(e) => setSipPassword(e.target.value)}
                                                placeholder="SIP Authentication Password"
                                                className="w-full px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                            />
                                        </div>
                                    </div>

                                    <p className="text-xs text-primary mt-3">
                                        <a href="#" className="hover:underline">Read more about using SIP with Callyy in the documentation</a>
                                    </p>
                                </div>
                            </div>
                        )}

                        {/* Twilio Import Form */}
                        {selectedProvider === 'Twilio' && (
                            <div className="space-y-4">
                                <div>
                                    <label className="block text-sm font-medium text-textMain mb-2">
                                        Twilio Phone Number
                                    </label>
                                    <div className="flex gap-2">
                                        <select className="px-3 py-2 bg-surface border border-border rounded-lg text-textMain">
                                            <option>🇺🇸</option>
                                        </select>
                                        <input
                                            type="text"
                                            value={twilioPhoneNumber}
                                            onChange={(e) => setTwilioPhoneNumber(e.target.value)}
                                            placeholder="+14156021922"
                                            className="flex-1 px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                        />
                                    </div>
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-textMain mb-2">
                                        Twilio Account SID
                                    </label>
                                    <input
                                        type="text"
                                        value={twilioAccountSid}
                                        onChange={(e) => setTwilioAccountSid(e.target.value)}
                                        placeholder="Twilio Account SID"
                                        className="w-full px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                    />
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-textMain mb-2">
                                        Twilio Auth Token
                                    </label>
                                    <input
                                        type="password"
                                        value={twilioAuthToken}
                                        onChange={(e) => setTwilioAuthToken(e.target.value)}
                                        placeholder="Twilio Auth Token"
                                        className="w-full px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                    />
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-textMain mb-2">
                                        Label
                                    </label>
                                    <input
                                        type="text"
                                        value={label}
                                        onChange={(e) => setLabel(e.target.value)}
                                        placeholder="Label for Phone Number"
                                        className="w-full px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                    />
                                </div>

                                <div className="flex items-center gap-3 p-4 bg-surface rounded-lg">
                                    <label className="relative inline-flex items-center cursor-pointer flex-1">
                                        <div className="flex-1">
                                            <div className="text-sm font-medium text-textMain">SMS Enabled</div>
                                            <div className="text-xs text-textMuted">Enable SMS messaging for this phone number</div>
                                        </div>
                                        <input
                                            type="checkbox"
                                            checked={smsEnabled}
                                            onChange={(e) => setSmsEnabled(e.target.checked)}
                                            className="sr-only peer"
                                        />
                                        <div className="w-11 h-6 bg-surface border-2 border-border rounded-full peer peer-checked:bg-primary peer-checked:border-primary transition-colors after:content-[''] after:absolute after:top-0.5 after:right-[22px] after:bg-textMuted after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:after:translate-x-full peer-checked:after:bg-background"></div>
                                    </label>
                                </div>
                            </div>
                        )}

                        {/* Vonage Import Form */}
                        {selectedProvider === 'Vonage' && (
                            <div className="space-y-4">
                                <div>
                                    <label className="block text-sm font-medium text-textMain mb-2">
                                        Vonage Phone Number
                                    </label>
                                    <div className="flex gap-2">
                                        <select className="px-3 py-2 bg-surface border border-border rounded-lg text-textMain">
                                            <option>🇺🇸</option>
                                        </select>
                                        <input
                                            type="text"
                                            value={vonagePhoneNumber}
                                            onChange={(e) => setVonagePhoneNumber(e.target.value)}
                                            placeholder="+14156021922"
                                            className="flex-1 px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                        />
                                    </div>
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-textMain mb-2">
                                        API Key
                                    </label>
                                    <input
                                        type="text"
                                        value={vonageApiKey}
                                        onChange={(e) => setVonageApiKey(e.target.value)}
                                        placeholder="Enter API Key"
                                        className="w-full px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                    />
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-textMain mb-2">
                                        API Secret
                                    </label>
                                    <input
                                        type="password"
                                        value={vonageApiSecret}
                                        onChange={(e) => setVonageApiSecret(e.target.value)}
                                        placeholder="Enter API Secret"
                                        className="w-full px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                    />
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-textMain mb-2">
                                        Label
                                    </label>
                                    <input
                                        type="text"
                                        value={label}
                                        onChange={(e) => setLabel(e.target.value)}
                                        placeholder="Label for Phone Number"
                                        className="w-full px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                    />
                                </div>
                            </div>
                        )}

                        {/* Telnyx Import Form */}
                        {selectedProvider === 'Telnyx' && (
                            <div className="space-y-4">
                                <div>
                                    <label className="block text-sm font-medium text-textMain mb-2">
                                        Telnyx Phone Number
                                    </label>
                                    <div className="flex gap-2">
                                        <select className="px-3 py-2 bg-surface border border-border rounded-lg text-textMain">
                                            <option>🇺🇸</option>
                                        </select>
                                        <input
                                            type="text"
                                            value={telnyxPhoneNumber}
                                            onChange={(e) => setTelnyxPhoneNumber(e.target.value)}
                                            placeholder="+14156021922"
                                            className="flex-1 px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                        />
                                    </div>
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-textMain mb-2">
                                        API Key
                                    </label>
                                    <input
                                        type="password"
                                        value={telnyxApiKey}
                                        onChange={(e) => setTelnyxApiKey(e.target.value)}
                                        placeholder="Enter API Key"
                                        className="w-full px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                    />
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-textMain mb-2">
                                        Label
                                    </label>
                                    <input
                                        type="text"
                                        value={label}
                                        onChange={(e) => setLabel(e.target.value)}
                                        placeholder="Label for Phone Number"
                                        className="w-full px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                    />
                                </div>
                            </div>
                        )}

                        {/* BYO SIP Trunk Form */}
                        {selectedProvider === 'BYOSIP' && (
                            <div className="space-y-4">
                                <div>
                                    <label className="block text-sm font-medium text-textMain mb-2">
                                        Phone Number
                                    </label>
                                    <input
                                        type="text"
                                        value={sipTrunkPhoneNumber}
                                        onChange={(e) => setSipTrunkPhoneNumber(e.target.value)}
                                        placeholder="+14155551234"
                                        className="w-full px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                    />
                                </div>

                                <div className="flex items-center gap-3 p-4 bg-surface rounded-lg">
                                    <label className="relative inline-flex items-center cursor-pointer flex-1">
                                        <div className="flex-1">
                                            <div className="text-sm font-medium text-textMain">Allow non-E164 phone numbers</div>
                                            <div className="text-xs text-textMuted">Check this box to disable E164 format validation and use custom phone number formats</div>
                                        </div>
                                        <input
                                            type="checkbox"
                                            checked={allowNonE164}
                                            onChange={(e) => setAllowNonE164(e.target.checked)}
                                            className="sr-only peer"
                                        />
                                        <div className="w-11 h-6 bg-surface border-2 border-border rounded-full peer peer-checked:bg-primary peer-checked:border-primary transition-colors after:content-[''] after:absolute after:top-0.5 after:right-[22px] after:bg-textMuted after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:after:translate-x-full peer-checked:after:bg-background"></div>
                                    </label>
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-textMain mb-2">
                                        SIP Trunk Credential
                                    </label>
                                    <select
                                        value={sipTrunkCredentialId}
                                        onChange={(e) => setSipTrunkCredentialId(e.target.value)}
                                        className="w-full px-4 py-2 bg-surface border border-border rounded-lg text-textMain focus:outline-none focus:ring-2 focus:ring-primary"
                                    >
                                        <option value="">Select a SIP trunk credential</option>
                                        {sipCredentials.map((cred) => (
                                            <option key={cred.id} value={cred.id}>
                                                {cred.name}
                                            </option>
                                        ))}
                                    </select>
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-textMain mb-2">
                                        Label
                                    </label>
                                    <input
                                        type="text"
                                        value={label}
                                        onChange={(e) => setLabel(e.target.value)}
                                        placeholder="Label for Phone Number"
                                        className="w-full px-4 py-2 bg-surface border border-border rounded-lg text-textMain placeholder-textMuted focus:outline-none focus:ring-2 focus:ring-primary"
                                    />
                                </div>

                                <p className="text-xs text-primary">
                                    <a href="#" className="hover:underline">Read more about SIP trunking in the documentation</a>
                                </p>
                            </div>
                        )}
                    </form>

                    {/* Footer */}
                    <div className="flex justify-end gap-3 p-6 border-t border-border">
                        <button
                            type="button"
                            onClick={handleClose}
                            className="px-6 py-2 bg-surface border border-border rounded-lg text-textMain hover:bg-surfaceHover transition-colors"
                        >
                            Cancel
                        </button>
                        <button
                            onClick={handleSubmit}
                            disabled={loading}
                            className={`px-6 py-2 rounded-lg font-semibold transition-colors ${
                                loading
                                    ? 'bg-primary/50 text-black/50 cursor-not-allowed'
                                    : 'bg-primary text-black hover:bg-primaryHover'
                            }`}
                        >
                            {loading ? 'Creating...' : 
                                selectedProvider === 'Callyy' ? 'Create' : 
                                selectedProvider === 'CallyySIP' ? 'Import SIP URI' :
                                selectedProvider === 'BYOSIP' ? 'Import SIP Phone Number' :
                                `Import from ${selectedProvider}`
                            }
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default PhoneNumberModal;
