-- Migration: create call_costs table
-- Generated by VN6 health check (2026-04-04)

CREATE TABLE IF NOT EXISTS call_costs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id),
  call_log_id UUID,
  tts_cost NUMERIC(10,6) DEFAULT 0,
  llm_cost NUMERIC(10,6) DEFAULT 0,
  telephony_cost NUMERIC(10,6) DEFAULT 0,
  total_cost NUMERIC(10,6) DEFAULT 0,
  credits_deducted INTEGER DEFAULT 0,
  breakdown JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE call_costs ENABLE ROW LEVEL SECURITY;

-- Policy: users can only see their own call costs
CREATE POLICY "Users can view own call costs" ON call_costs
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Service role full access" ON call_costs
  USING (true)
  WITH CHECK (true);
