#!/bin/bash
# ============================================
# LiveKit Self-Hosted Setup for GCP
# ============================================
# This script sets up LiveKit server on your local machine or GCE VM
# 
# Prerequisites:
# - Docker and Docker Compose installed
# - GCP CLI configured (for cloud deployment)
#
# Usage:
#   ./setup.sh local    # Run locally with Docker Compose
#   ./setup.sh gce      # Deploy to GCE VM
#   ./setup.sh keys     # Generate new API keys
# ============================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Generate LiveKit API keys
generate_keys() {
    log_info "Generating LiveKit API keys..."
    
    # Generate random API key and secret
    API_KEY="API$(openssl rand -hex 8)"
    API_SECRET="$(openssl rand -base64 32 | tr -d '/+=' | head -c 40)"
    
    echo ""
    echo "============================================"
    echo "LiveKit API Credentials (SAVE THESE!)"
    echo "============================================"
    echo "LIVEKIT_API_KEY=$API_KEY"
    echo "LIVEKIT_API_SECRET=$API_SECRET"
    echo "============================================"
    echo ""
    
    # Save to .env file
    cat > .env << EOF
# LiveKit Configuration
LIVEKIT_API_KEY=$API_KEY
LIVEKIT_API_SECRET=$API_SECRET
LIVEKIT_URL=ws://localhost:7880

# AI Provider Keys (add your own)
OPENAI_API_KEY=your-openai-key
DEEPGRAM_API_KEY=your-deepgram-key
ELEVENLABS_API_KEY=your-elevenlabs-key

# Supabase (from your backend/.env)
SUPABASE_URL=https://YOUR_SUPABASE_PROJECT_REF.supabase.co
SUPABASE_SERVICE_ROLE_KEY=your-service-role-key
EOF
    
    log_success "API keys saved to .env"
    log_warn "Remember to update the AI provider keys in .env!"
}

# Update livekit.yaml with generated keys
update_config() {
    if [ ! -f .env ]; then
        log_error ".env file not found. Run './setup.sh keys' first."
        exit 1
    fi
    
    source .env
    
    log_info "Updating livekit.yaml with API keys..."
    
    # Create updated config
    cat > livekit.yaml << EOF
# LiveKit Server Configuration
# Auto-generated by setup.sh

port: 7880
bind_addresses:
  - ""

rtc:
  port_range_start: 50000
  port_range_end: 50100
  tcp_port: 7881
  use_external_ip: true

keys:
  $LIVEKIT_API_KEY: $LIVEKIT_API_SECRET

logging:
  level: info

room:
  enabled_codecs:
    - mime: audio/opus
    - mime: audio/red
  max_participants: 10
  empty_timeout: 300s
  departure_timeout: 30s

turn:
  enabled: true
  udp_port: 3478
  tls_port: 5349

region: local
EOF
    
    log_success "livekit.yaml updated"
}

# Run locally with Docker Compose
run_local() {
    log_info "Starting LiveKit locally with Docker Compose..."
    
    if [ ! -f .env ]; then
        log_warn ".env not found. Generating keys first..."
        generate_keys
        update_config
    fi
    
    # Check Docker
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed. Please install Docker first."
        exit 1
    fi
    
    # Pull latest images
    log_info "Pulling Docker images..."
    docker compose pull
    
    # Start services
    log_info "Starting services..."
    docker compose up -d
    
    # Wait for startup
    log_info "Waiting for services to start..."
    sleep 5
    
    # Check health
    if curl -s http://localhost:7880 > /dev/null 2>&1; then
        log_success "LiveKit server is running at ws://localhost:7880"
    else
        log_warn "LiveKit server may still be starting. Check with: docker compose logs livekit-server"
    fi
    
    echo ""
    echo "============================================"
    echo "LiveKit is running!"
    echo "============================================"
    echo "Server URL: ws://localhost:7880"
    echo "HTTP URL:   http://localhost:7880"
    echo ""
    echo "To view logs: docker compose logs -f"
    echo "To stop:      docker compose down"
    echo "============================================"
}

# Stop local services
stop_local() {
    log_info "Stopping LiveKit services..."
    docker compose down
    log_success "Services stopped"
}

# Deploy to GCE VM
deploy_gce() {
    log_info "Deploying LiveKit to GCE VM..."
    
    if [ ! -f .env ]; then
        log_error ".env not found. Run './setup.sh keys' first."
        exit 1
    fi
    
    source .env
    
    # GCE configuration
    PROJECT_ID="${GCP_PROJECT_ID:-voicory}"
    ZONE="${GCE_ZONE:-asia-south1-a}"
    INSTANCE_NAME="${GCE_INSTANCE:-livekit-server}"
    MACHINE_TYPE="${GCE_MACHINE_TYPE:-e2-medium}"
    
    log_info "Creating GCE VM: $INSTANCE_NAME in $ZONE..."
    
    # Create VM with Container-Optimized OS
    gcloud compute instances create-with-container "$INSTANCE_NAME" \
        --project="$PROJECT_ID" \
        --zone="$ZONE" \
        --machine-type="$MACHINE_TYPE" \
        --container-image="livekit/livekit-server:latest" \
        --container-env="LIVEKIT_KEYS=${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}" \
        --tags="livekit-server" \
        --metadata="google-logging-enabled=true" \
        || log_error "Failed to create VM. It may already exist."
    
    # Create firewall rules
    log_info "Creating firewall rules..."
    
    gcloud compute firewall-rules create livekit-http \
        --project="$PROJECT_ID" \
        --allow=tcp:7880 \
        --target-tags=livekit-server \
        --description="LiveKit HTTP/WebSocket" \
        2>/dev/null || log_warn "Firewall rule livekit-http may already exist"
    
    gcloud compute firewall-rules create livekit-rtc \
        --project="$PROJECT_ID" \
        --allow=tcp:7881 \
        --target-tags=livekit-server \
        --description="LiveKit RTC TCP" \
        2>/dev/null || log_warn "Firewall rule livekit-rtc may already exist"
    
    gcloud compute firewall-rules create livekit-udp \
        --project="$PROJECT_ID" \
        --allow=udp:50000-50100 \
        --target-tags=livekit-server \
        --description="LiveKit WebRTC UDP" \
        2>/dev/null || log_warn "Firewall rule livekit-udp may already exist"
    
    gcloud compute firewall-rules create livekit-turn \
        --project="$PROJECT_ID" \
        --allow=udp:3478,tcp:5349 \
        --target-tags=livekit-server \
        --description="LiveKit TURN" \
        2>/dev/null || log_warn "Firewall rule livekit-turn may already exist"
    
    # Get external IP
    EXTERNAL_IP=$(gcloud compute instances describe "$INSTANCE_NAME" \
        --project="$PROJECT_ID" \
        --zone="$ZONE" \
        --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
    
    log_success "GCE VM deployed!"
    echo ""
    echo "============================================"
    echo "LiveKit Server Deployed to GCE"
    echo "============================================"
    echo "External IP: $EXTERNAL_IP"
    echo "WebSocket:   ws://$EXTERNAL_IP:7880"
    echo "HTTP:        http://$EXTERNAL_IP:7880"
    echo ""
    echo "Update your .env files:"
    echo "  LIVEKIT_URL=ws://$EXTERNAL_IP:7880"
    echo "============================================"
}

# Deploy voice agent to Cloud Run
deploy_agent() {
    log_info "Deploying Voice Agent to Cloud Run..."
    
    if [ ! -f .env ]; then
        log_error ".env not found. Run './setup.sh keys' first."
        exit 1
    fi
    
    source .env
    
    PROJECT_ID="${GCP_PROJECT_ID:-voicory}"
    REGION="${GCP_REGION:-asia-south1}"
    SERVICE_NAME="voicory-voice-agent"
    
    # Build and push image
    log_info "Building voice agent Docker image..."
    cd agent
    
    gcloud builds submit \
        --project="$PROJECT_ID" \
        --tag="gcr.io/$PROJECT_ID/$SERVICE_NAME" \
        .
    
    # Deploy to Cloud Run
    log_info "Deploying to Cloud Run..."
    gcloud run deploy "$SERVICE_NAME" \
        --project="$PROJECT_ID" \
        --region="$REGION" \
        --image="gcr.io/$PROJECT_ID/$SERVICE_NAME" \
        --platform=managed \
        --allow-unauthenticated \
        --memory=1Gi \
        --cpu=1 \
        --min-instances=1 \
        --max-instances=10 \
        --set-env-vars="LIVEKIT_URL=$LIVEKIT_URL" \
        --set-env-vars="LIVEKIT_API_KEY=$LIVEKIT_API_KEY" \
        --set-env-vars="LIVEKIT_API_SECRET=$LIVEKIT_API_SECRET" \
        --set-env-vars="OPENAI_API_KEY=$OPENAI_API_KEY" \
        --set-env-vars="DEEPGRAM_API_KEY=$DEEPGRAM_API_KEY" \
        --set-env-vars="ELEVENLABS_API_KEY=$ELEVENLABS_API_KEY" \
        --set-env-vars="SUPABASE_URL=$SUPABASE_URL" \
        --set-env-vars="SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY"
    
    log_success "Voice agent deployed to Cloud Run!"
}

# Show help
show_help() {
    echo "LiveKit Setup Script for Voicory"
    echo ""
    echo "Usage: ./setup.sh <command>"
    echo ""
    echo "Commands:"
    echo "  keys        Generate new LiveKit API keys"
    echo "  local       Run LiveKit locally with Docker Compose"
    echo "  stop        Stop local Docker services"
    echo "  gce         Deploy LiveKit server to GCE VM"
    echo "  agent       Deploy voice agent to Cloud Run"
    echo "  help        Show this help message"
    echo ""
    echo "Quick Start (Local Development):"
    echo "  1. ./setup.sh keys     # Generate API keys"
    echo "  2. Edit .env with your AI provider keys"
    echo "  3. ./setup.sh local    # Start LiveKit"
    echo ""
    echo "Production Deployment:"
    echo "  1. ./setup.sh keys     # Generate API keys"
    echo "  2. Edit .env with all required keys"
    echo "  3. ./setup.sh gce      # Deploy LiveKit to GCE"
    echo "  4. ./setup.sh agent    # Deploy voice agent to Cloud Run"
}

# Main
case "${1:-help}" in
    keys)
        generate_keys
        update_config
        ;;
    local)
        run_local
        ;;
    stop)
        stop_local
        ;;
    gce)
        deploy_gce
        ;;
    agent)
        deploy_agent
        ;;
    help|--help|-h)
        show_help
        ;;
    *)
        log_error "Unknown command: $1"
        show_help
        exit 1
        ;;
esac
